name: Build and publish Android library

on:
  pull_request:

jobs:
  build:
    name: "Build Android library"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Rust toolchain
        run: rustup show

      - name: Build
        run: >
          ./gradlew assembleRelease &&
          jar tvf $( find . -name '*-release.aar' ) |
          grep '\.so$'
#        env:
#          NDK_VERSION: "25.0.8775105"
#          
