name: Build and publish Android library

on:
  push:

jobs:
  build:
    name: "Build and publish Android library"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Rust toolchain
        run: rustup show

      - name: Build
        run: >
          ./gradlew assembleRelease &&
          jar tvf $( find . -name '*-release.aar' ) |
          grep '\.so$'

