name: Build and publish Android library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and publish Android library"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        run: rustup show

      - name: Build
        run: ./gradlew assembleRelease

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          files: |
            ./artiwrapper/build/outputs/aar/artiwrapper-release.aar
          tag_name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
